### ISSUE TITLE
Set up extension to get @jupyterlab/csvviewer and @lumino/datagrid from forked verisons of Jupyterlab and Lumino

### ISSUE THREAD

**Issue by lmcnichols** [jupytercalpoly/jupyterlab-tabular-data-editor#21]
We would like to be able to modify some of the attributes in `DSVModel` class https://github.com/lmcnichols/jupyterlab/blob/master/packages/csvviewer/src/model.ts and the `DataGrid` class https://github.com/jupyterlab/lumino/blob/master/packages/datagrid/src/datagrid.ts. However, many of the attributes & methods we would like to change are set to `private`.

As a fix, we would like to have our extension depend on some node modules which come from Jupyterlab and Lumino forks on our local repository. In these forks, we would modify the source code so that the `private` attributes we need are set to `protected`.

We haven't figured out a way to set a dependency to a subdirectory of a git repository. This is a known issue (see https://github.com/yarnpkg/yarn/issues/4725 and https://github.com/npm/npm/issues/2974). Attempts to use existing tools (e.g. https://gitpkg.now.sh/) have failed, although we are still unclear on why they are failing.

**Comment by saulshanabrook** [comment]
Hey @lmcnichols!

Yeah this is a tricky problem. A couple of options on your end:

1. Publish your fork of the lumino CSV viewer as another package (rename it to some other package name) and import from there. This will let anyone who installs your package pull in the desired lumino fork.
2. Set the version of `@lumino/datagrid` to a `file://` package pointing to your local edits. You don't have to change the name here, but it will only work locally for development, not for end user install.
3. Do a version of the above, but when building your extension [pre-build it with webpack](https://github.com/saulshanabrook/jupyterlab-webpack) so that forked lumino source is essentially inlined into the build. Then you don't have to depend on any `@lumino/datagrid` extension.

I am happy to jump on a call with you, to talk about this more, if that would be helpful, feel free to reach out at s.shanabrook@gmail.com to set up a time to chat.

**Comment by kgoo124** [comment]
As of right now, we have decided to publish our own npm package `tde-csviewer` to handle the necessary changes for our extension to work. These changes will soon be requested as a PR into JupyterLab core
